### ISSUE TITLE
Why do i get a ValueError: The number of weights does not match the population when i run it for 13 and above number of cities

### ISSUE THREAD

**Issue by Harryking120903** [klima7/TSP-Ant-System#1]
Why do i get a ValueError: The number of weights does not match the population when i run it for 13 and above number of cities 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/100433794/233833853-5dd921b1-e2c2-4824-be6c-9355a3820671.png">
<img width="669" alt="image" src="https://user-images.githubusercontent.com/100433794/233833865-4ffaf7f0-9e04-4a64-9ee5-92718aaaebdb.png">

**Comment by klima7** [comment]
Just fixed in 13ea441b357b70aea74aff59ca2318f01861b5c4
